### ISSUE TITLE
Missing session.secret key

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian#269]
At random places, we see this:

```
Traceback (most recent call last):
  File "/home/hajime/.virtualenvs/librarian/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/hajime/code/librarian/librarian/core/contrib/databases/plugins.py", line 11, in wrapper
    return callback(*args, **kwargs)
  File "/home/hajime/code/librarian/librarian/core/contrib/sessions/plugins.py", line 37, in wrapper
    return callback(*args, **kwargs)
  File "/home/hajime/code/librarian/librarian/core/contrib/auth/plugins.py", line 32, in wrapper
    return callback(*args, **kwargs)
  File "/home/hajime/.virtualenvs/librarian/lib/python2.7/site-packages/bottle_utils/i18n.py", line 387, in wrapper
    return callback(*args, **kwargs)
  File "/home/hajime/.virtualenvs/librarian/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/hajime/code/librarian/librarian/plugins/__init__.py", line 5, in wrapper
    return fn(*args, **kwargs)
  File "/home/hajime/.virtualenvs/librarian/lib/python2.7/site-packages/bottle_utils/ajax.py", line 68, in wrapper
    result = func(*args, **kwargs)
  File "/home/hajime/.virtualenvs/librarian/lib/python2.7/site-packages/bottle_utils/csrf.py", line 90, in wrapper
    secret, token_name, path, expires = get_conf()
  File "/home/hajime/.virtualenvs/librarian/lib/python2.7/site-packages/bottle_utils/csrf.py", line 27, in get_conf
    csrf_secret = conf['csrf.secret']
  File "/home/hajime/.virtualenvs/librarian/lib/python2.7/site-packages/confloader.py", line 206, in __getitem__
    raise ConfigurationFormatError(err)
ConfigurationFormatError: Configuration error in section [csrf]: missing 'secret' setting
```

**Comment by integricho** [comment]
Fixed when setup module was reintegrated with the collectors API.
