### ISSUE TITLE
Facets: Guaranteed  facets keys not present for some files

### ISSUE THREAD

**Issue by goodbadwolf** [Outernet-Project/librarian#271]
```
Traceback (most recent call last):
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_core/contrib/databases/plugins.py", line 11, in wrapper
    return callback(*args, **kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_core/contrib/sessions/plugins.py", line 37, in wrapper
    return callback(*args, **kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_core/contrib/auth/plugins.py", line 32, in wrapper
    return callback(*args, **kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/bottle_utils/i18n.py", line 387, in wrapper
    return callback(*args, **kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_setup/plugins.py", line 25, in wrapper
    return callback(*args, **kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_captive/plugins.py", line 26, in wrapper
    return callback(*args, **kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_filemanager/routes.py", line 303, in init_file_action
    return show_view(path, view, defaults)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_filemanager/routes.py", line 183, in show_view
    return show_list_view(path, view, defaults)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/bottle_utils/ajax.py", line 72, in wrapper
    return templ(tpl_name, **tplvars)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/bottle.py", line 3609, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_core/contrib/templates/renderer.py", line 44, in render
    return self.tpl.render(**_defaults)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/librarian/librarian/tmp/mako_cache/base.tpl.py", line 169, in render_body
    context['self'].main(**pageargs)
  File "filemanager_main", line 208, in render_main
  File "/home/librarian/librarian/tmp/mako_cache/filemanager/_main.tpl.py", line 131, in render_body
    __M_writer(unicode(current_view.body()))
  File "/home/librarian/librarian/tmp/mako_cache/filemanager/_audio.tpl.py", line 38, in render_body
    __M_writer(unicode(self.view_main()))
  File "/home/librarian/librarian/tmp/mako_cache/filemanager/_audio.tpl.py", line 86, in render_view_main
    __M_writer(unicode(metadata.get('title') or titlify(metadata.get('file'))))
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_filemanager/helpers.py", line 53, in title_name
    name, _ = os.path.splitext(path)
  File "/home/librarian/.virtualenvs/librarian/lib/python2.7/posixpath.py", line 105, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/home/librarian/.virtualenvs/librarian/lib/python2.7/genericpath.py", line 91, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by integricho** [comment]
Fixed in #dafe79f7c5a06d226725de97ad7144548a4a8238
