### ISSUE TITLE
Facets: Exception in HTML metadata extract

### ISSUE THREAD

**Issue by goodbadwolf** [Outernet-Project/librarian#272]
```
KeyError: u'language'
    self.data['language'] == meta.get('content')
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_content/facets/metadata.py", line 216, in __init__
    meta = HtmlMetadata(self.fsal, path)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_content/facets/processors.py", line 151, in _get_metadata
    meta, assets = self._get_metadata(path, partial)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_content/facets/processors.py", line 137, in process_file
    processor.process_file(facets, path)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_content/facets/archive.py", line 150, in update_facets
    facets_archive.update_facets(fpath)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_content/tasks.py", line 58, in check_new_content
    changes_found = fn(supervisor)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/librarian_content/tasks.py", line 29, in wrapper
    fn(*args, **kwargs)
  File "/home/librarian/.virtualenvs/librarian/local/lib/python2.7/site-packages/greentasks/scheduler.py", line 35, in _execute
Traceback (most recent call last):
```

**Comment by ben-en** [comment]
Fixed in PR #278
