### ISSUE TITLE
Default configuration as generated by `make prepare` raises errors on develop branch

### ISSUE THREAD

**Issue by ben-en** [Outernet-Project/librarian#305]
Branch: `develop`

When following the documentation, attempting to start librarian with `make prepare; librarian --conf tmp/librarian.ini` results in the following traceback.

```
SQL: SELECT version FROM migrations WHERE name = %(name)s;
Database set meta installed for librarian
SQL: SELECT version FROM migrations WHERE name = %(name)s;
Database set notifications installed for librarian
SQL: SELECT version FROM migrations WHERE name = %(name)s;
Database set sessions installed for librarian.core.contrib.sessions
SQL: SELECT version FROM migrations WHERE name = %(name)s;
Database set auth installed for librarian.core.contrib.auth
Could not import member routes.filemanager.List from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/filemanager.py", line 16, in <module>
    from streamline import NonIterableRouteBase, XHRPartialRoute, TemplateFormRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.filemanager.Details from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/filemanager.py", line 16, in <module>
    from streamline import NonIterableRouteBase, XHRPartialRoute, TemplateFormRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.filemanager.Direct from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/filemanager.py", line 16, in <module>
    from streamline import NonIterableRouteBase, XHRPartialRoute, TemplateFormRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.filemanager.Delete from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/filemanager.py", line 16, in <module>
    from streamline import NonIterableRouteBase, XHRPartialRoute, TemplateFormRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.filemanager.Thumb from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/filemanager.py", line 16, in <module>
    from streamline import NonIterableRouteBase, XHRPartialRoute, TemplateFormRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.logs.SendAppLog from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/logs.py", line 7, in <module>
    from streamline import NonIterableRouteBase
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.logs.SendDiag from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/logs.py", line 7, in <module>
    from streamline import NonIterableRouteBase
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.setup.Enter from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/setup.py", line 13, in <module>
    from streamline import NonIterableRouteBase, TemplateRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.setup.Exit from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/setup.py", line 13, in <module>
    from streamline import NonIterableRouteBase, TemplateRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.setup.Diag from librarian
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/routes/setup.py", line 13, in <module>
    from streamline import NonIterableRouteBase, TemplateRoute
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.StaticRoute from librarian.core.contrib.assets
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/core/contrib/assets/routes.py", line 5, in <module>
    from streamline import NonIterableRouteBase
ImportError: cannot import name NonIterableRouteBase
Could not import member routes.FaviconRoute from librarian.core.contrib.assets
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 325, in collect
    obj = component.get_object(name)
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 181, in get_object
    return import_object(self.fully_qualified_name(name))
  File "/home/ben/repos/librarian/librarian/core/utils/collectors.py", line 65, in import_object
    mod = importlib.import_module(mod)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ben/repos/librarian/librarian/core/contrib/assets/routes.py", line 5, in <module>
    from streamline import NonIterableRouteBase
ImportError: cannot import name NonIterableRouteBase
An error occurred during `init_complete`.
Traceback (most recent call last):
  File "/home/ben/repos/librarian/librarian/core/supervisor.py", line 140, in boot
    self.exts.exports.process_components()
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 532, in process_components
    collector.install()
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 302, in install
    for member in self.get_ordered_members():
  File "/home/ben/repos/librarian/librarian/core/exports.py", line 430, in get_ordered_members
    ordered = self.resolver.solve()
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/disentangler.py", line 112, in solve
    self._order_nodes()
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/disentangler.py", line 103, in _order_nodes
    for dep_id in self._collect_dependencies(node_id):
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/disentangler.py", line 93, in _collect_dependencies
    self._collect_dependencies(dep_id, collected=collected)
  File "/home/ben/.envs/librarian/lib/python2.7/site-packages/disentangler.py", line 79, in _collect_dependencies
    raise self.UnresolvableDependency(node_id)
UnresolvableDependency: sys:static
```

**Comment by integricho** [comment]
Fixed with a03aabab3ec8188b0ec1b18f647d19f354f6a8bd and 52bc2958007f30ecca7d4dbb89dcd3eb32057267
